# [Manipulate data the MXNet way with `ndarray`](http://gluon.mxnet.io/chapter01_crashcourse/ndarray.html)

It’s impossible to get anything done if we can’t manipulate data.  
Generally, there are two important things we need to do with it:  
(i) acquire it!  
(ii) process it once it’s inside the computer.  
There’s no point in trying to acquire data if we don’t even know how to store it, so let’s get our hands dirty first by playing with synthetic data.  

We’ll start by introducing NDArrays, MXNet’s primary tool for storing and transforming data.  
If you’ve worked with NumPy before, you’ll notice that NDArrays are, by design, similar to NumPy’s multi-dimensional array.  
However, they confer a few key advantages.  
First, NDArrays support asynchronous computation on CPU, GPU, and distributed cloud architectures.  
Second, they provide support for automatic differentiation.  
These properties make NDArray an ideal library for machine learning, both for researchers and engineers launching production systems.

## [Getting Started](http://gluon.mxnet.io/chapter01_crashcourse/ndarray.html#Getting-started)

In this chapter, we’ll get you going with the basic functionality.  
Don’t worry if you don’t understand any of the basic math, like element-wise operations or normal distributions.  
In the next two chapters we’ll take another pass at NDArray, teaching you both the math you’ll need and how to realize it in code.  
To get started, let’s import `mxnet`.  
We’ll also import `ndarray` from `mxnet` for convenience.  
We’ll make a habit of setting a random seed so that you always get the same results that we do.

In [58]:
import mxnet as mx
from mxnet import nd
mx.random.seed(1)

Next, let's see how to create an NDArray without any values initialized.  
Specifically, we'll create a 2D array (a matrix) with 3 rows and 4 columns.

In [59]:
x = nd.empty((3, 4))
print(x)


[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
<NDArray 3x4 @cpu(0)>


The `empty` method just grabs some memory and hands us back a matrix without setting the values of any of its entries.  
This means that the entries can have any form of values, including very big ones!  
But typically, we’ll want our matrices initialized.  
Commonly, we want a matrix of all zeros.

In [60]:
x = nd.zeros((3, 5))
x


[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]
<NDArray 3x5 @cpu(0)>

Similarly, `ndarray` has a function to create a matrix of all ones.

In [61]:
x = nd.ones((3, 4))
x


[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]
<NDArray 3x4 @cpu(0)>

Often, we’ll want to create arrays whose values are sampled randomly.  
This is especially common when we intend to use the array as a parameter in a neural network.  
In this snippet, we initialize with values drawn from a standard normal distribution with zero mean and unit variance.

In [62]:
y = nd.random_normal(0, 1, shape=(3,4))
y


[[ 0.03629481 -0.49024421 -0.95017916  0.03751944]
 [-0.72984636 -2.04010558  1.482131    1.04082799]
 [-0.45256865  0.31160426 -0.83673781 -0.78830057]]
<NDArray 3x4 @cpu(0)>

Just like in NumPy, the dimensions of each NDArray are accessible with the `.shape` attribute:

In [63]:
y.shape

(3, 4)

We can also query its size, which is equal to the product of the components of the shape.  
Together witht the precision of the stored values, this tells us how much memory the array occupies.

In [64]:
y.size

12

## [Operations](http://gluon.mxnet.io/chapter01_crashcourse/ndarray.html#Operations)

NDArray supports a large number of standard mathematical operations.

In [65]:
# Element-wise addition:
x + y


[[ 1.03629482  0.50975579  0.04982084  1.03751945]
 [ 0.27015364 -1.04010558  2.482131    2.04082799]
 [ 0.54743135  1.31160426  0.16326219  0.21169943]]
<NDArray 3x4 @cpu(0)>

In [66]:
# Multiplication:
x * y


[[ 0.03629481 -0.49024421 -0.95017916  0.03751944]
 [-0.72984636 -2.04010558  1.482131    1.04082799]
 [-0.45256865  0.31160426 -0.83673781 -0.78830057]]
<NDArray 3x4 @cpu(0)>

In [67]:
# Exponentiation:
nd.exp(y)


[[ 1.03696156  0.61247683  0.38667175  1.03823221]
 [ 0.48198304  0.13001499  4.40231705  2.83156061]
 [ 0.63599241  1.36561418  0.43312114  0.45461673]]
<NDArray 3x4 @cpu(0)>

Here we can use a matrix's transpose to compute a proper matrix-matrix product:

In [68]:
nd.dot(x, y.T)


[[-1.3666091  -0.24699283 -1.76600277]
 [-1.3666091  -0.24699283 -1.76600277]
 [-1.3666091  -0.24699283 -1.76600277]]
<NDArray 3x3 @cpu(0)>

We’ll explain these operations and present even more operators in the [linear algebra chapter](http://gluon.mxnet.io/chapter01_crashcourse/linear-algebra.html).  
But for now, we’ll stick with the mechanics of working with NDArrays.

## [In-place operations](http://gluon.mxnet.io/chapter01_crashcourse/ndarray.html#In-place-operations)

In the previous example, every time we ran an operation, we allocated new memory to host its results.  
For example, if we write `y = x + y`, we will dereference the matrix that `y` used to point to and instead change the pointer to the newly allocated memory.  
In the following example we demonstrate this with Python’s `id()` function, which gives us the exact address of the referenced object in memory.  
After running `y = y + x`, we’ll find that `id(y)` points to a different location.  
That’s because Python first evaluates `y + x`, allocating new memory for the result and then subsequently redirects `y` to point at this new location in memory.  
Now read that last part again if you have any questions.  

In [69]:
print('Memory location of y: ', id(y))
y = y + x
print('Memory location of y: ', id(y))

Memory location of y:  4554944128
Memory location of y:  4554964440


This might be undesirable for two reasons.  
First, we don’t want to run around allocating memory unnecessarily all the time.  
In machine learning, we might have hundreds of megabytes of parameters and update all of them multiple times per second.  
Typically, we’ll want to perform these updates in place.  
Second, we might point at the same parameters from multiple variables.  
If we don’t update in place, this could cause a memory leak, and could cause us to inadvertently reference stale parameters.  
Fortunately, performing in-place operations in MXNet is easy.  
We can assign the result of an operation to a previously allocated array with slice notation, e.g., `y[:] = <expression>`.

In [70]:
print('Memory location of y: ', id(y))
y[:] = y + x
print('Memory location of y: ', id(y))

Memory location of y:  4554964440
Memory location of y:  4554964440


While this is syntactically nice, `x + y` here will still allocate a temporary buffer to store the result before copying it to `y[:]`.  
To make even better use of memory, we can directly invoke the underlying ndarray operation, in this case `elemwise_add`, avoiding temporary buffers.  
We do this by specifying the `out` keyword argument, which every `ndarray` operator supports:

In [71]:
nd.elemwise_add(x, y, out=y)


[[ 3.03629494  2.50975585  2.0498209   3.03751945]
 [ 2.27015352  0.95989442  4.482131    4.04082775]
 [ 2.54743147  3.31160426  2.16326213  2.21169949]]
<NDArray 3x4 @cpu(0)>

If we’re not planning to re-use `x`, then we can assign the result to `x` itself.  
There are two ways to do this in MXNet.  
1. By using slice notation `x[:] = x op y`.  
2. By using the op-equals operators like `+=`.  

In [72]:
print('Memory location of x: ', id(x))
x += y
x
print('Memory location of x: ', id(x))

Memory location of x:  4554944296
Memory location of x:  4554944296


## [Slicing](http://gluon.mxnet.io/chapter01_crashcourse/ndarray.html#Slicing)