# [Manipulate data the MXNet way with `ndarray`](http://gluon.mxnet.io/chapter01_crashcourse/ndarray.html)

It’s impossible to get anything done if we can’t manipulate data.  
Generally, there are two important things we need to do with it:  
(i) acquire it!  
(ii) process it once it’s inside the computer.  
There’s no point in trying to acquire data if we don’t even know how to store it, so let’s get our hands dirty first by playing with synthetic data.  

We’ll start by introducing NDArrays, MXNet’s primary tool for storing and transforming data.  
If you’ve worked with NumPy before, you’ll notice that NDArrays are, by design, similar to NumPy’s multi-dimensional array.  
However, they confer a few key advantages.  
First, NDArrays support asynchronous computation on CPU, GPU, and distributed cloud architectures.  
Second, they provide support for automatic differentiation.  
These properties make NDArray an ideal library for machine learning, both for researchers and engineers launching production systems.

## [Getting Started](http://gluon.mxnet.io/chapter01_crashcourse/ndarray.html#Getting-started)

In this chapter, we’ll get you going with the basic functionality.  
Don’t worry if you don’t understand any of the basic math, like element-wise operations or normal distributions.  
In the next two chapters we’ll take another pass at NDArray, teaching you both the math you’ll need and how to realize it in code.  
To get started, let’s import `mxnet`.  
We’ll also import `ndarray` from `mxnet` for convenience.  
We’ll make a habit of setting a random seed so that you always get the same results that we do.

In [20]:
import mxnet as mx
from mxnet import nd
mx.random.seed(1)

Next, let's see how to create an NDArray without any values initialized.  
Specifically, we'll create a 2D array (a matrix) with 3 rows and 4 columns.

In [21]:
x = nd.empty((3, 4))
print(x)


[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
<NDArray 3x4 @cpu(0)>


The `empty` method just grabs some memory and hands us back a matrix without setting the values of any of its entries.  
This means that the entries can have any form of values, including very big ones!  
But typically, we’ll want our matrices initialized.  
Commonly, we want a matrix of all zeros.

In [22]:
x = nd.zeros((3, 5))
x


[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]
<NDArray 3x5 @cpu(0)>

Similarly, `ndarray` has a function to create a matrix of all ones.

In [23]:
x = nd.ones((3, 4))
x


[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]
<NDArray 3x4 @cpu(0)>

Often, we’ll want to create arrays whose values are sampled randomly.  
This is especially common when we intend to use the array as a parameter in a neural network.  
In this snippet, we initialize with values drawn from a standard normal distribution with zero mean and unit variance.

In [24]:
y = nd.random_normal(0, 1, shape=(3,4))
y


[[ 0.03629481 -0.49024421 -0.95017916  0.03751944]
 [-0.72984636 -2.04010558  1.482131    1.04082799]
 [-0.45256865  0.31160426 -0.83673781 -0.78830057]]
<NDArray 3x4 @cpu(0)>

Just like in NumPy, the dimensions of each NDArray are accessible with the `.shape` attribute:

In [25]:
y.shape

(3, 4)

We can also query its size, which is equal to the product of the components of the shape.  
Together witht the precision of the stored values, this tells us how much memory the array occupies.

In [26]:
y.size

12

### [Operations](http://gluon.mxnet.io/chapter01_crashcourse/ndarray.html#Operations)