# [Pandas Cookbook](https://pandas.pydata.org/pandas-docs/stable/cookbook.html)

In [74]:
import pandas as pd
import numpy as np

## [Idioms](https://pandas.pydata.org/pandas-docs/stable/cookbook.html#idioms)

### [If-then-else](https://pandas.pydata.org/pandas-docs/stable/cookbook.html#if-then)

[Override calculations and reassign variables:](https://stackoverflow.com/questions/17128302/python-pandas-idiom-for-if-then-else)

In [75]:
df = pd.DataFrame({'AAA' : [4,5,6,7],
                  'BBB' : [10,20,30,40],
                  'CCC' : [100,50,-30,-50]})
df

AAA  BBB  CCC
0    4   10  100
1    5   20   50
2    6   30  -30
3    7   40  -50

Execute an if-then statement on one column:

In [76]:
# If AAA >= 5, BBB = -1
df.loc[df.AAA >= 5, 'BBB'] = -1; df

AAA  BBB  CCC
0    4   10  100
1    5   -1   50
2    6   -1  -30
3    7   -1  -50

If-then with assignment to 2 columns:

In [77]:
df.loc[df.AAA >= 5, ['BBB','CCC']] = 555; df

AAA  BBB  CCC
0    4   10  100
1    5  555  555
2    6  555  555
3    7  555  555

Now you can perform another operation on the first row:

In [78]:
df.loc[df.AAA < 5, ['BBB', 'CCC']] = 2000; df

AAA   BBB   CCC
0    4  2000  2000
1    5   555   555
2    6   555   555
3    7   555   555

You can also use pandas after setting up a mask:

In [79]:
df_mask = pd.DataFrame({'AAA' : [True] * 4, 'BBB' : [False] * 4, 'CCC' : [True,False] * 2})
df_mask

AAA    BBB    CCC
0  True  False   True
1  True  False  False
2  True  False   True
3  True  False  False

In [80]:
df.where(df_mask, -1000)

AAA   BBB   CCC
0    4 -1000  2000
1    5 -1000 -1000
2    6 -1000   555
3    7 -1000 -1000

[Use numpy's where() to perform an if-then-else operation](https://stackoverflow.com/questions/19913659/pandas-conditional-creation-of-a-series-dataframe-column).  
In other words, the conditional creation of a DataFrame column:

In [81]:
df = pd.DataFrame({'AAA' : [4,5,6,7], 'BBB' : [10,20,30,40], 'CCC' : [100,50,-30,-50]}); df

AAA  BBB  CCC
0    4   10  100
1    5   20   50
2    6   30  -30
3    7   40  -50

In [82]:
# New column -- if AAA > 5, then high, else low:
df['logic'] = np.where(df['AAA'] > 5,'high','low'); df

AAA  BBB  CCC logic
0    4   10  100   low
1    5   20   50   low
2    6   30  -30  high
3    7   40  -50  high

### [Splitting](https://pandas.pydata.org/pandas-docs/stable/cookbook.html#splitting)

[Split a frame based on a boolean value:](https://stackoverflow.com/questions/14957116/how-to-split-a-dataframe-according-to-a-boolean-criterion)

In [83]:
df = pd.DataFrame({'AAA' : [4,5,6,7], 'BBB' : [10,20,30,40], 'CCC' : [100,50,-30,-50]}); df

AAA  BBB  CCC
0    4   10  100
1    5   20   50
2    6   30  -30
3    7   40  -50

In [84]:
df_low = df[df.AAA <= 5]; df_low

AAA  BBB  CCC
0    4   10  100
1    5   20   50

In [85]:
df_high = df[df.AAA > 5]; df_high

AAA  BBB  CCC
2    6   30  -30
3    7   40  -50

### [Building Criteria](https://pandas.pydata.org/pandas-docs/stable/cookbook.html#building-criteria)

[Select with multi-column criteria:](https://stackoverflow.com/questions/15315452/selecting-with-complex-criteria-from-pandas-dataframe)

In [86]:
df = pd.DataFrame({'AAA' : [4,5,6,7], 'BBB' : [10,20,30,40],'CCC' : [100,50,-30,-50]}); df

AAA  BBB  CCC
0    4   10  100
1    5   20   50
2    6   30  -30
3    7   40  -50

In [87]:
# And operation without assignment:
newseries = df.loc[(df['BBB'] < 25) & (df['CCC'] >= -40), 'AAA']; newseries

0    4
1    5
Name: AAA, dtype: int64

In [88]:
# Or operation without assignment:
newseries = df.loc[(df['BBB'] > 25) | (df['CCC'] >= -40), 'AAA']; newseries

0    4
1    5
2    6
3    7
Name: AAA, dtype: int64

In [89]:
# Or operation with assignment modifies the dataframe:
df.loc[(df['BBB'] > 25) | (df['CCC'] >= 75), 'AAA'] = 0.1; df

AAA  BBB  CCC
0  0.1   10  100
1  5.0   20   50
2  0.1   30  -30
3  0.1   40  -50

[Select the rows with data that's closest to a target value:](https://stackoverflow.com/questions/17758023/return-rows-in-a-dataframe-closest-to-a-user-defined-number)

In [90]:
df = pd.DataFrame({'AAA' : [4,5,6,7], 'BBB' : [10,20,30,40],'CCC' : [100,50,-30,-50]}); df

AAA  BBB  CCC
0    4   10  100
1    5   20   50
2    6   30  -30
3    7   40  -50

In [91]:
aValue = 43.0
df.loc[(df.CCC-aValue).abs().argsort()]

AAA  BBB  CCC
1    5   20   50
0    4   10  100
2    6   30  -30
3    7   40  -50

[Dynamically reduce a list of criteria using binary operators](https://stackoverflow.com/questions/21058254/pandas-boolean-operation-in-a-python-list/21058331)

In [92]:
df = pd.DataFrame({'AAA' : [4,5,6,7], 'BBB' : [10,20,30,40], 'CCC' : [100,50,-30,-50]}); df

AAA  BBB  CCC
0    4   10  100
1    5   20   50
2    6   30  -30
3    7   40  -50

In [93]:
Crit1 = df.AAA <= 5.5; Crit1

0     True
1     True
2    False
3    False
Name: AAA, dtype: bool

In [94]:
Crit2 = df.BBB == 10.0; Crit2

0     True
1    False
2    False
3    False
Name: BBB, dtype: bool

In [95]:
Crit3 = df.CCC > -40.0; Crit3

0     True
1     True
2     True
3    False
Name: CCC, dtype: bool

If you want to hard code a solution:

In [96]:
AllCrit = Crit1 & Crit2 & Crit3; AllCrit

0     True
1    False
2    False
3    False
dtype: bool

You may want to work with a list of dynamically built criteria:

In [97]:
CritList = [Crit1,Crit2,Crit3]; CritList

[0     True
 1     True
 2    False
 3    False
 Name: AAA, dtype: bool, 0     True
 1    False
 2    False
 3    False
 Name: BBB, dtype: bool, 0     True
 1     True
 2     True
 3    False
 Name: CCC, dtype: bool]

In [98]:
import functools

AllCrit = functools.reduce(lambda x,y: x & y, CritList); AllCrit

0     True
1    False
2    False
3    False
dtype: bool

In [99]:
df[AllCrit]

AAA  BBB  CCC
0    4   10  100

## [Selection](https://pandas.pydata.org/pandas-docs/stable/cookbook.html#selection)

### DataFrames

Ladies and gentleman, [The Indexing Documentation](https://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing)

[Pandas using row labels in boolean indexing](https://stackoverflow.com/questions/14725068/pandas-using-row-labels-in-boolean-indexing)

In [100]:
# Using both row labels and value conditionals:
df = pd.DataFrame({'AAA' : [4,5,6,7], 'BBB' : [10,20,30,40], 'CCC' : [100,50,-30,50]}); df

AAA  BBB  CCC
0    4   10  100
1    5   20   50
2    6   30  -30
3    7   40   50

In [101]:
df[(df.AAA <= 6) & (df.index.isin([0,2,4]))]

AAA  BBB  CCC
0    4   10  100
2    6   30  -30

[Use `loc` for label-oriented slicing and `iloc` for positional slicing](https://github.com/pandas-dev/pandas/issues/2904)

In [102]:
data = {'AAA' : [4,5,6,7], 'BBB' : [10,20,30,40], 'CCC' : [100,50,-30,50]}
pd.DataFrame(data)

AAA  BBB  CCC
0    4   10  100
1    5   20   50
2    6   30  -30
3    7   40   50

In [103]:
df = pd.DataFrame(data=data,index=['foo','bar','goo','car']); df

AAA  BBB  CCC
foo    4   10  100
bar    5   20   50
goo    6   30  -30
car    7   40   50

There are two explicit slicing methods and an available third option:
1. Positional-oriented ( Python slicing style : exclusive end )
2. Label-oriented ( Non-Python slicing style : inclusive end )
3. General ( Either slicing style : depends on slicing on labels or positions )

In [104]:
# Label-oriented:
df.loc['bar' : 'car']

AAA  BBB  CCC
bar    5   20   50
goo    6   30  -30
car    7   40   50

In [105]:
# Positional-oriented:
df.iloc[0:3]

AAA  BBB  CCC
foo    4   10  100
bar    5   20   50
goo    6   30  -30

Ambiguity arises when an index consists of integers with a non-zero start or non-unit increment.

In [106]:
# Begin index at 1 instead of 0
df2 = pd.DataFrame(data=data,index=[1,2,3,4]); df2

AAA  BBB  CCC
1    4   10  100
2    5   20   50
3    6   30  -30
4    7   40   50

In [107]:
df2.iloc[1:3]

AAA  BBB  CCC
2    5   20   50
3    6   30  -30

In [108]:
df2.loc[1:3]

AAA  BBB  CCC
1    4   10  100
2    5   20   50
3    6   30  -30

[Using the inverse operator `~` to take the complement of a mask](https://stackoverflow.com/questions/14986510/picking-out-elements-based-on-complement-of-indices-in-python-pandas)

In [109]:
df = pd.DataFrame({'AAA' : [4,5,6,7], 'BBB' : [10,20,30,40], 'CCC' : [100,50,-30,-50]}); df

AAA  BBB  CCC
0    4   10  100
1    5   20   50
2    6   30  -30
3    7   40  -50

In [110]:
df[~((df.AAA <= 6) & (df.index.isin([0,2,4])))]

AAA  BBB  CCC
1    5   20   50
3    7   40  -50

### Panels

[Extend a panel frame by transposing, adding a new dimension, and transposing back to the original dimensions](https://stackoverflow.com/questions/15364050/extending-a-pandas-panel-frame-along-the-minor-axis)

In [111]:
rng = pd.date_range('1/1/2018',periods=100,freq='D')

In [112]:
data = np.random.randn(100,4)

In [113]:
print(rng[:5])
print()
print(data[:5])
cols = ['A','B','C','D']; cols

DatetimeIndex(['2018-01-01', '2018-01-02', '2018-01-03', '2018-01-04',
               '2018-01-05'],
              dtype='datetime64[ns]', freq='D')

[[ 0.24486894  0.77782416 -0.06265165 -0.28303814]
 [-0.50759347 -0.11119892  1.31300175 -0.10765738]
 [ 1.76475636 -0.51239998 -0.6996354  -0.00939992]
 [ 2.16866876  0.35962548  0.58225477 -0.8472472 ]
 [ 2.45328474  1.30166355  2.3147043   0.37899709]]


['A', 'B', 'C', 'D']

In [114]:
# Another reason why Python is so wonderful:
df1, df2, df3 = pd.DataFrame(data, rng, cols), pd.DataFrame(data, rng, cols), pd.DataFrame(data, rng, cols)
df1[:5]

A         B         C         D
2018-01-01  0.244869  0.777824 -0.062652 -0.283038
2018-01-02 -0.507593 -0.111199  1.313002 -0.107657
2018-01-03  1.764756 -0.512400 -0.699635 -0.009400
2018-01-04  2.168669  0.359625  0.582255 -0.847247
2018-01-05  2.453285  1.301664  2.314704  0.378997

In [115]:
pf = pd.Panel({'df1':df1,'df2':df2,'df3':df3});pf

<class 'pandas.core.panel.Panel'>
Dimensions: 3 (items) x 100 (major_axis) x 4 (minor_axis)
Items axis: df1 to df3
Major_axis axis: 2018-01-01 00:00:00 to 2018-04-10 00:00:00
Minor_axis axis: A to D

In [116]:
pf.loc[:,:,'F'] = pd.DataFrame(data,rng,cols);pf

<class 'pandas.core.panel.Panel'>
Dimensions: 3 (items) x 100 (major_axis) x 5 (minor_axis)
Items axis: df1 to df3
Major_axis axis: 2018-01-01 00:00:00 to 2018-04-10 00:00:00
Minor_axis axis: A to F

### New Columns