# [Pandas Cookbook](https://pandas.pydata.org/pandas-docs/stable/cookbook.html)

In [163]:
import pandas as pd
import numpy as np

## [Idioms](https://pandas.pydata.org/pandas-docs/stable/cookbook.html#idioms)

### [If-then-else](https://pandas.pydata.org/pandas-docs/stable/cookbook.html#if-then)

[Override calculations and reassign variables:](https://stackoverflow.com/questions/17128302/python-pandas-idiom-for-if-then-else)

In [164]:
df = pd.DataFrame({'AAA' : [4,5,6,7],
                  'BBB' : [10,20,30,40],
                  'CCC' : [100,50,-30,-50]})
df

AAA  BBB  CCC
0    4   10  100
1    5   20   50
2    6   30  -30
3    7   40  -50

Execute an if-then statement on one column:

In [165]:
# If AAA >= 5, BBB = -1
df.loc[df.AAA >= 5, 'BBB'] = -1; df

AAA  BBB  CCC
0    4   10  100
1    5   -1   50
2    6   -1  -30
3    7   -1  -50

If-then with assignment to 2 columns:

In [166]:
df.loc[df.AAA >= 5, ['BBB','CCC']] = 555; df

AAA  BBB  CCC
0    4   10  100
1    5  555  555
2    6  555  555
3    7  555  555

Now you can perform another operation on the first row:

In [167]:
df.loc[df.AAA < 5, ['BBB', 'CCC']] = 2000; df

AAA   BBB   CCC
0    4  2000  2000
1    5   555   555
2    6   555   555
3    7   555   555

You can also use pandas after setting up a mask:

In [168]:
df_mask = pd.DataFrame({'AAA' : [True] * 4, 'BBB' : [False] * 4, 'CCC' : [True,False] * 2})
df_mask

AAA    BBB    CCC
0  True  False   True
1  True  False  False
2  True  False   True
3  True  False  False

In [169]:
df.where(df_mask, -1000)

AAA   BBB   CCC
0    4 -1000  2000
1    5 -1000 -1000
2    6 -1000   555
3    7 -1000 -1000

[Use numpy's where() to perform an if-then-else operation](https://stackoverflow.com/questions/19913659/pandas-conditional-creation-of-a-series-dataframe-column).  
In other words, the conditional creation of a DataFrame column:

In [170]:
df = pd.DataFrame({'AAA' : [4,5,6,7], 'BBB' : [10,20,30,40], 'CCC' : [100,50,-30,-50]}); df

AAA  BBB  CCC
0    4   10  100
1    5   20   50
2    6   30  -30
3    7   40  -50

In [171]:
# New column -- if AAA > 5, then high, else low:
df['logic'] = np.where(df['AAA'] > 5,'high','low'); df

AAA  BBB  CCC logic
0    4   10  100   low
1    5   20   50   low
2    6   30  -30  high
3    7   40  -50  high

### [Splitting](https://pandas.pydata.org/pandas-docs/stable/cookbook.html#splitting)

[Split a frame based on a boolean value:](https://stackoverflow.com/questions/14957116/how-to-split-a-dataframe-according-to-a-boolean-criterion)

In [172]:
df = pd.DataFrame({'AAA' : [4,5,6,7], 'BBB' : [10,20,30,40], 'CCC' : [100,50,-30,-50]}); df

AAA  BBB  CCC
0    4   10  100
1    5   20   50
2    6   30  -30
3    7   40  -50

In [173]:
df_low = df[df.AAA <= 5]; df_low

AAA  BBB  CCC
0    4   10  100
1    5   20   50

In [174]:
df_high = df[df.AAA > 5]; df_high

AAA  BBB  CCC
2    6   30  -30
3    7   40  -50

### [Building Criteria](https://pandas.pydata.org/pandas-docs/stable/cookbook.html#building-criteria)

[Select with multi-column criteria:](https://stackoverflow.com/questions/15315452/selecting-with-complex-criteria-from-pandas-dataframe)

In [175]:
df = pd.DataFrame({'AAA' : [4,5,6,7], 'BBB' : [10,20,30,40],'CCC' : [100,50,-30,-50]}); df

AAA  BBB  CCC
0    4   10  100
1    5   20   50
2    6   30  -30
3    7   40  -50

In [176]:
# And operation without assignment:
newseries = df.loc[(df['BBB'] < 25) & (df['CCC'] >= -40), 'AAA']; newseries

0    4
1    5
Name: AAA, dtype: int64

In [177]:
# Or operation without assignment:
newseries = df.loc[(df['BBB'] > 25) | (df['CCC'] >= -40), 'AAA']; newseries

0    4
1    5
2    6
3    7
Name: AAA, dtype: int64

In [178]:
# Or operation with assignment modifies the dataframe:
df.loc[(df['BBB'] > 25) | (df['CCC'] >= 75), 'AAA'] = 0.1; df

AAA  BBB  CCC
0  0.1   10  100
1  5.0   20   50
2  0.1   30  -30
3  0.1   40  -50

[Select the rows with data that's closest to a target value:](https://stackoverflow.com/questions/17758023/return-rows-in-a-dataframe-closest-to-a-user-defined-number)

In [179]:
df = pd.DataFrame({'AAA' : [4,5,6,7], 'BBB' : [10,20,30,40],'CCC' : [100,50,-30,-50]}); df

AAA  BBB  CCC
0    4   10  100
1    5   20   50
2    6   30  -30
3    7   40  -50

In [180]:
aValue = 43.0
df.loc[(df.CCC-aValue).abs().argsort()]

AAA  BBB  CCC
1    5   20   50
0    4   10  100
2    6   30  -30
3    7   40  -50

[Dynamically reduce a list of criteria using binary operators](https://stackoverflow.com/questions/21058254/pandas-boolean-operation-in-a-python-list/21058331)

In [181]:
df = pd.DataFrame({'AAA' : [4,5,6,7], 'BBB' : [10,20,30,40], 'CCC' : [100,50,-30,-50]}); df

AAA  BBB  CCC
0    4   10  100
1    5   20   50
2    6   30  -30
3    7   40  -50

In [182]:
Crit1 = df.AAA <= 5.5; Crit1

0     True
1     True
2    False
3    False
Name: AAA, dtype: bool

In [183]:
Crit2 = df.BBB == 10.0; Crit2

0     True
1    False
2    False
3    False
Name: BBB, dtype: bool

In [184]:
Crit3 = df.CCC > -40.0; Crit3

0     True
1     True
2     True
3    False
Name: CCC, dtype: bool

If you want to hard code a solution:

In [185]:
AllCrit = Crit1 & Crit2 & Crit3; AllCrit

0     True
1    False
2    False
3    False
dtype: bool

You may want to work with a list of dynamically built criteria:

In [186]:
CritList = [Crit1,Crit2,Crit3]; CritList

[0     True
 1     True
 2    False
 3    False
 Name: AAA, dtype: bool, 0     True
 1    False
 2    False
 3    False
 Name: BBB, dtype: bool, 0     True
 1     True
 2     True
 3    False
 Name: CCC, dtype: bool]

In [187]:
import functools

AllCrit = functools.reduce(lambda x,y: x & y, CritList); AllCrit

0     True
1    False
2    False
3    False
dtype: bool

In [188]:
df[AllCrit]

AAA  BBB  CCC
0    4   10  100

## [Selection](https://pandas.pydata.org/pandas-docs/stable/cookbook.html#selection)

### DataFrames

Ladies and gentleman, [The Indexing Documentation](https://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing)

[Pandas using row labels in boolean indexing](https://stackoverflow.com/questions/14725068/pandas-using-row-labels-in-boolean-indexing)

In [189]:
# Using both row labels and value conditionals:
df = pd.DataFrame({'AAA' : [4,5,6,7], 'BBB' : [10,20,30,40], 'CCC' : [100,50,-30,50]}); df

AAA  BBB  CCC
0    4   10  100
1    5   20   50
2    6   30  -30
3    7   40   50

In [190]:
df[(df.AAA <= 6) & (df.index.isin([0,2,4]))]

AAA  BBB  CCC
0    4   10  100
2    6   30  -30

[Use `loc` for label-oriented slicing and `iloc` for positional slicing](https://github.com/pandas-dev/pandas/issues/2904)

In [191]:
data = {'AAA' : [4,5,6,7], 'BBB' : [10,20,30,40], 'CCC' : [100,50,-30,50]}
pd.DataFrame(data)

AAA  BBB  CCC
0    4   10  100
1    5   20   50
2    6   30  -30
3    7   40   50

In [192]:
df = pd.DataFrame(data=data,index=['foo','bar','goo','car']); df

AAA  BBB  CCC
foo    4   10  100
bar    5   20   50
goo    6   30  -30
car    7   40   50

There are two explicit slicing methods and an available third option:
1. Positional-oriented ( Python slicing style : exclusive end )
2. Label-oriented ( Non-Python slicing style : inclusive end )
3. General ( Either slicing style : depends on slicing on labels or positions )

In [193]:
# Label-oriented:
df.loc['bar' : 'car']

AAA  BBB  CCC
bar    5   20   50
goo    6   30  -30
car    7   40   50

In [194]:
# Positional-oriented:
df.iloc[0:3]

AAA  BBB  CCC
foo    4   10  100
bar    5   20   50
goo    6   30  -30

Ambiguity arises when an index consists of integers with a non-zero start or non-unit increment.

In [195]:
# Begin index at 1 instead of 0
df2 = pd.DataFrame(data=data,index=[1,2,3,4]); df2

AAA  BBB  CCC
1    4   10  100
2    5   20   50
3    6   30  -30
4    7   40   50

In [196]:
df2.iloc[1:3]

AAA  BBB  CCC
2    5   20   50
3    6   30  -30

In [197]:
df2.loc[1:3]

AAA  BBB  CCC
1    4   10  100
2    5   20   50
3    6   30  -30

[Using the inverse operator `~` to take the complement of a mask](https://stackoverflow.com/questions/14986510/picking-out-elements-based-on-complement-of-indices-in-python-pandas)

In [198]:
df = pd.DataFrame({'AAA' : [4,5,6,7], 'BBB' : [10,20,30,40], 'CCC' : [100,50,-30,-50]}); df

AAA  BBB  CCC
0    4   10  100
1    5   20   50
2    6   30  -30
3    7   40  -50

In [199]:
df[~((df.AAA <= 6) & (df.index.isin([0,2,4])))]

AAA  BBB  CCC
1    5   20   50
3    7   40  -50

### Panels

[Extend a panel frame by transposing, adding a new dimension, and transposing back to the original dimensions](https://stackoverflow.com/questions/15364050/extending-a-pandas-panel-frame-along-the-minor-axis)

In [200]:
rng = pd.date_range('1/1/2018',periods=100,freq='D')

In [201]:
data = np.random.randn(100,4)

In [202]:
print(rng[:5])
print()
print(data[:5])
cols = ['A','B','C','D']; cols

DatetimeIndex(['2018-01-01', '2018-01-02', '2018-01-03', '2018-01-04',
               '2018-01-05'],
              dtype='datetime64[ns]', freq='D')

[[ 2.12424661 -0.02555919 -1.13060277 -0.25371292]
 [ 0.46207639  0.56320476  1.04509406 -0.05545555]
 [-0.72036572 -0.8051265  -0.36289445 -0.73994101]
 [ 0.61874512 -0.16428785 -0.22466701  0.24201406]
 [-1.65574472 -1.08845807  0.53906948 -0.62134173]]


['A', 'B', 'C', 'D']

In [203]:
# Another reason why Python is so wonderful:
df1, df2, df3 = pd.DataFrame(data, rng, cols), pd.DataFrame(data, rng, cols), pd.DataFrame(data, rng, cols)
df1[:5]

A         B         C         D
2018-01-01  2.124247 -0.025559 -1.130603 -0.253713
2018-01-02  0.462076  0.563205  1.045094 -0.055456
2018-01-03 -0.720366 -0.805126 -0.362894 -0.739941
2018-01-04  0.618745 -0.164288 -0.224667  0.242014
2018-01-05 -1.655745 -1.088458  0.539069 -0.621342

In [204]:
pf = pd.Panel({'df1':df1,'df2':df2,'df3':df3});pf

<class 'pandas.core.panel.Panel'>
Dimensions: 3 (items) x 100 (major_axis) x 4 (minor_axis)
Items axis: df1 to df3
Major_axis axis: 2018-01-01 00:00:00 to 2018-04-10 00:00:00
Minor_axis axis: A to D

In [205]:
pf.loc[:,:,'F'] = pd.DataFrame(data,rng,cols);pf

<class 'pandas.core.panel.Panel'>
Dimensions: 3 (items) x 100 (major_axis) x 5 (minor_axis)
Items axis: df1 to df3
Major_axis axis: 2018-01-01 00:00:00 to 2018-04-10 00:00:00
Minor_axis axis: A to F

### New Columns

[Create new columns using `applymap()`](https://stackoverflow.com/questions/16575868/efficiently-creating-additional-columns-in-a-pandas-dataframe-using-map)

In [206]:
df = pd.DataFrame({'AAA' : [1,2,1,3], 'BBB' : [1,1,2,2], 'CCC' : [2,1,3,1]}); df

AAA  BBB  CCC
0    1    1    2
1    2    1    1
2    1    2    3
3    3    2    1

In [207]:
source_cols = df.columns  # any subset would work
source_cols

Index(['AAA', 'BBB', 'CCC'], dtype='object')

In [208]:
new_cols = [str(x) + "_cat" for x in source_cols]
new_cols

['AAA_cat', 'BBB_cat', 'CCC_cat']

In [209]:
categories = { 1 : 'Alpha', 2 : 'Beta', 3 : 'Charlie' }
df[new_cols] = df[source_cols].applymap(categories.get); df

AAA  BBB  CCC  AAA_cat BBB_cat  CCC_cat
0    1    1    2    Alpha   Alpha     Beta
1    2    1    1     Beta   Alpha    Alpha
2    1    2    3    Alpha    Beta  Charlie
3    3    2    1  Charlie    Beta    Alpha

[Keep other columns when using `min()` with `groupby`](https://stackoverflow.com/questions/23394476/keep-other-columns-when-using-min-with-groupby)

In [210]:
df = pd.DataFrame({'AAA' : [1,1,1,2,2,2,3,3], 'BBB' : [2,1,3,4,5,1,2,3]}); df

AAA  BBB
0    1    2
1    1    1
2    1    3
3    2    4
4    2    5
5    2    1
6    3    2
7    3    3

In [211]:
# Method 1 -- use idxmin() to get the index of the mins:
df.loc[df.groupby('AAA')['BBB'].idxmin()]

AAA  BBB
1    1    1
5    2    1
6    3    2

In [212]:
# Method 2 -- sort the entries, then take the first of each.
# Notice that the resulting dataframe is the same except for the index.
df.sort_values(by='BBB').groupby('AAA', as_index=False).first()

AAA  BBB
0    1    1
1    2    1
2    3    2

## [MultiIndexing](https://pandas.pydata.org/pandas-docs/stable/cookbook.html#multiindexing)

Ladies and Gentleman, The [MultiIndexing Documentation](https://pandas.pydata.org/pandas-docs/stable/advanced.html#advanced-hierarchical).

[Creating a multi-index from a labeled frame](https://stackoverflow.com/questions/14916358/reshaping-dataframes-in-pandas-based-on-column-labels)

In [213]:
df = pd.DataFrame({'Row' : [0,1,2],
                 'one_X' : [1.1,1.1,1.1],
                 'one_Y' : [1.2,1.2,1.2],
                 'two_X' : [1.11,1.11,1.11],
                 'two_Y' : [1.22,1.22,1.22]})
df

Row  one_X  one_Y  two_X  two_Y
0    0    1.1    1.2   1.11   1.22
1    1    1.1    1.2   1.11   1.22
2    2    1.1    1.2   1.11   1.22

In [214]:
# As a labeled index:
df = df.set_index('Row'); df

one_X  one_Y  two_X  two_Y
Row                            
0      1.1    1.2   1.11   1.22
1      1.1    1.2   1.11   1.22
2      1.1    1.2   1.11   1.22

In [215]:
# With hierarchical columns:
df.columns = pd.MultiIndex.from_tuples([tuple(c.split('_')) for c in df.columns]); df

one        two      
       X    Y     X     Y
Row                      
0    1.1  1.2  1.11  1.22
1    1.1  1.2  1.11  1.22
2    1.1  1.2  1.11  1.22

In [216]:
# Now you can stack and reset them:
df = df.stack(0).reset_index(1); df

level_1     X     Y
Row                    
0       one  1.10  1.20
0       two  1.11  1.22
1       one  1.10  1.20
1       two  1.11  1.22
2       one  1.10  1.20
2       two  1.11  1.22

In [217]:
# Notice how the label 'level_1' got added for you in the DataFrame above.
# You can fix your own labels, too:
df.columns = ['Sample','All_X', 'All_Y']; df

Sample  All_X  All_Y
Row                     
0      one   1.10   1.20
0      two   1.11   1.22
1      one   1.10   1.20
1      two   1.11   1.22
2      one   1.10   1.20
2      two   1.11   1.22

### Arithmetic

[Performing arithmetic with a multi-index that needs broadcasting](https://stackoverflow.com/questions/19501510/divide-entire-pandas-multiindex-dataframe-by-dataframe-variable/19502176#19502176)

In [218]:
cols = pd.MultiIndex.from_tuples([(x,y) for x in ['A','B','C'] for y in ['O','I']]); cols

MultiIndex(levels=[['A', 'B', 'C'], ['I', 'O']],
           labels=[[0, 0, 1, 1, 2, 2], [1, 0, 1, 0, 1, 0]])

In [219]:
df = pd.DataFrame(cols); df

0
0  (A, O)
1  (A, I)
2  (B, O)
3  (B, I)
4  (C, O)
5  (C, I)

In [220]:
df = pd.DataFrame(np.random.randn(2,6),index=['n','m'],columns=cols); df

A                   B                   C          
          O         I         O         I         O         I
n  0.263889  1.109737 -0.239560 -1.331106  0.585886 -2.290841
m  0.744188 -0.041993 -0.564314  0.649121  0.440187  2.268096

In [221]:
df = df.div(df['C'],level=1); df

A                   B              C     
          O         I         O         I    O    I
n  0.450410 -0.484423 -0.408884  0.581056  1.0  1.0
m  1.690616 -0.018515 -1.281986  0.286197  1.0  1.0

In [222]:
df = df.div(df['B'],level=1); df

A              B              C          
          O         I    O    I         O         I
n -1.101557 -0.833695  1.0  1.0 -2.445679  1.721005
m -1.318748 -0.064692  1.0  1.0 -0.780040  3.494102

## [Slicing](https://pandas.pydata.org/pandas-docs/stable/cookbook.html#slicing)

[Slicing a multi-index with `xs`](https://stackoverflow.com/questions/12590131/how-to-slice-multindex-columns-in-pandas-dataframes)

In [223]:
coords = [('AA','one'),('AA','six'),('BB','one'),('BB','two'),('BB','six')]
df = pd.DataFrame(coords); df

0    1
0  AA  one
1  AA  six
2  BB  one
3  BB  two
4  BB  six

In [224]:
index = pd.MultiIndex.from_tuples(coords); index

MultiIndex(levels=[['AA', 'BB'], ['one', 'six', 'two']],
           labels=[[0, 0, 1, 1, 1], [0, 1, 0, 2, 1]])

In [225]:
df = pd.DataFrame(index); df

0
0  (AA, one)
1  (AA, six)
2  (BB, one)
3  (BB, two)
4  (BB, six)

In [226]:
df = pd.DataFrame([11,22,33,44,55],index,['MyData']); df

MyData
AA one      11
   six      22
BB one      33
   two      44
   six      55

In [227]:
# Take the cross section of the 1st level and 1st axis
df.xs('BB',level=0,axis=0)

MyData
one      33
two      44
six      55

In [228]:
# Now take the 2nd level of the first axis
df.xs('six',level=1,axis=0)

MyData
AA      22
BB      55

[Navigating the indices in a MultiIndex](https://stackoverflow.com/questions/14964493/multiindex-based-indexing-in-pandas)  
Another way to slice a multi-index using the `xs()` method.

In [229]:
import itertools

index = list(itertools.product(['Ada','Quinn','Violet'],['Comp','Math','Sci'])); index

[('Ada', 'Comp'),
 ('Ada', 'Math'),
 ('Ada', 'Sci'),
 ('Quinn', 'Comp'),
 ('Quinn', 'Math'),
 ('Quinn', 'Sci'),
 ('Violet', 'Comp'),
 ('Violet', 'Math'),
 ('Violet', 'Sci')]

In [230]:
headr = list(itertools.product(['Exams','Labs'],['I','II'])); headr

[('Exams', 'I'), ('Exams', 'II'), ('Labs', 'I'), ('Labs', 'II')]

In [231]:
indx = pd.MultiIndex.from_tuples(index,names=['Student','Course']); indx

MultiIndex(levels=[['Ada', 'Quinn', 'Violet'], ['Comp', 'Math', 'Sci']],
           labels=[[0, 0, 0, 1, 1, 1, 2, 2, 2], [0, 1, 2, 0, 1, 2, 0, 1, 2]],
           names=['Student', 'Course'])

In [232]:
pd.DataFrame(indx)

0
0     (Ada, Comp)
1     (Ada, Math)
2      (Ada, Sci)
3   (Quinn, Comp)
4   (Quinn, Math)
5    (Quinn, Sci)
6  (Violet, Comp)
7  (Violet, Math)
8   (Violet, Sci)

In [233]:
# Notice that the labelsin the cols multi-index are unnamed
cols = pd.MultiIndex.from_tuples(headr); cols

MultiIndex(levels=[['Exams', 'Labs'], ['I', 'II']],
           labels=[[0, 0, 1, 1], [0, 1, 0, 1]])

In [234]:
data = [[70+x+y+(x*y)%3 for x in range(4)] for y in range(9)]; data

[[70, 71, 72, 73],
 [71, 73, 75, 74],
 [72, 75, 75, 75],
 [73, 74, 75, 76],
 [74, 76, 78, 77],
 [75, 78, 78, 78],
 [76, 77, 78, 79],
 [77, 79, 81, 80],
 [78, 81, 81, 81]]

In [235]:
df = pd.DataFrame(data,indx,cols); df

Exams     Labs    
                   I  II    I  II
Student Course                   
Ada     Comp      70  71   72  73
        Math      71  73   75  74
        Sci       72  75   75  75
Quinn   Comp      73  74   75  76
        Math      74  76   78  77
        Sci       75  78   78  78
Violet  Comp      76  77   78  79
        Math      77  79   81  80
        Sci       78  81   81  81

In [236]:
# https://stackoverflow.com/questions/38208416/colon-none-slicenone-in-numpy-array-indexers
All = slice(None); All

slice(None, None, None)

In [237]:
df.loc['Violet']

Exams     Labs    
           I  II    I  II
Course                   
Comp      76  77   78  79
Math      77  79   81  80
Sci       78  81   81  81

In [238]:
df.loc['Violet']

Exams     Labs    
           I  II    I  II
Course                   
Comp      76  77   78  79
Math      77  79   81  80
Sci       78  81   81  81

In [239]:
df.loc[(All,'Math'),All]

Exams     Labs    
                   I  II    I  II
Student Course                   
Ada     Math      71  73   75  74
Quinn   Math      74  76   78  77
Violet  Math      77  79   81  80

In [240]:
df.loc[(slice('Ada','Quinn'),'Math'),All]

Exams     Labs    
                   I  II    I  II
Student Course                   
Ada     Math      71  73   75  74
Quinn   Math      74  76   78  77

In [241]:
df.loc[(All,'Math'),('Exams')]

I  II
Student Course        
Ada     Math    71  73
Quinn   Math    74  76
Violet  Math    77  79

In [242]:
df.loc[(All,'Math'),(All,'II')]

Exams Labs
                  II   II
Student Course           
Ada     Math      73   74
Quinn   Math      76   77
Violet  Math      79   80

Having fun yet?  
Check out [this Stack Overflow post](https://stackoverflow.com/questions/19319432/pandas-selecting-a-lower-level-in-a-dataframe-to-do-a-ffill) on how to tinker with the numbers on different levels of a MultiIndex.

## [Sorting](https://pandas.pydata.org/pandas-docs/stable/cookbook.html#sorting)