# [Pandas Cookbook](https://pandas.pydata.org/pandas-docs/stable/cookbook.html)

In [1]:
import pandas as pd
import numpy as np

## [Idioms](https://pandas.pydata.org/pandas-docs/stable/cookbook.html#idioms)

### [If-then-else](https://pandas.pydata.org/pandas-docs/stable/cookbook.html#if-then)

[Override calculations and reassign variables:](https://stackoverflow.com/questions/17128302/python-pandas-idiom-for-if-then-else)

In [2]:
df = pd.DataFrame({'AAA' : [4,5,6,7],
                  'BBB' : [10,20,30,40],
                  'CCC' : [100,50,-30,-50]})
df

AAA  BBB  CCC
0    4   10  100
1    5   20   50
2    6   30  -30
3    7   40  -50

Execute an if-then statement on one column:

In [3]:
# If AAA >= 5, BBB = -1
df.loc[df.AAA >= 5, 'BBB'] = -1; df

AAA  BBB  CCC
0    4   10  100
1    5   -1   50
2    6   -1  -30
3    7   -1  -50

If-then with assignment to 2 columns:

In [4]:
df.loc[df.AAA >= 5, ['BBB','CCC']] = 555; df

AAA  BBB  CCC
0    4   10  100
1    5  555  555
2    6  555  555
3    7  555  555

Now you can perform another operation on the first row:

In [5]:
df.loc[df.AAA < 5, ['BBB', 'CCC']] = 2000; df

AAA   BBB   CCC
0    4  2000  2000
1    5   555   555
2    6   555   555
3    7   555   555

You can also use pandas after setting up a mask:

In [6]:
df_mask = pd.DataFrame({'AAA' : [True] * 4, 'BBB' : [False] * 4, 'CCC' : [True,False] * 2})
df_mask

AAA    BBB    CCC
0  True  False   True
1  True  False  False
2  True  False   True
3  True  False  False

In [7]:
df.where(df_mask, -1000)

AAA   BBB   CCC
0    4 -1000  2000
1    5 -1000 -1000
2    6 -1000   555
3    7 -1000 -1000

[Use numpy's where() to perform an if-then-else operation](https://stackoverflow.com/questions/19913659/pandas-conditional-creation-of-a-series-dataframe-column).  
In other words, the conditional creation of a DataFrame column:

In [8]:
df = pd.DataFrame({'AAA' : [4,5,6,7], 'BBB' : [10,20,30,40], 'CCC' : [100,50,-30,-50]}); df

AAA  BBB  CCC
0    4   10  100
1    5   20   50
2    6   30  -30
3    7   40  -50

In [9]:
# New column -- if AAA > 5, then high, else low:
df['logic'] = np.where(df['AAA'] > 5,'high','low'); df

AAA  BBB  CCC logic
0    4   10  100   low
1    5   20   50   low
2    6   30  -30  high
3    7   40  -50  high

### [Splitting](https://pandas.pydata.org/pandas-docs/stable/cookbook.html#splitting)

[Split a frame based on a boolean value:](https://stackoverflow.com/questions/14957116/how-to-split-a-dataframe-according-to-a-boolean-criterion)

In [10]:
df = pd.DataFrame({'AAA' : [4,5,6,7], 'BBB' : [10,20,30,40], 'CCC' : [100,50,-30,-50]}); df

AAA  BBB  CCC
0    4   10  100
1    5   20   50
2    6   30  -30
3    7   40  -50

In [11]:
df_low = df[df.AAA <= 5]; df_low

AAA  BBB  CCC
0    4   10  100
1    5   20   50

In [12]:
df_high = df[df.AAA > 5]; df_high

AAA  BBB  CCC
2    6   30  -30
3    7   40  -50

### [Building Criteria](https://pandas.pydata.org/pandas-docs/stable/cookbook.html#building-criteria)

[Select with multi-column criteria:](https://stackoverflow.com/questions/15315452/selecting-with-complex-criteria-from-pandas-dataframe)

In [13]:
df = pd.DataFrame({'AAA' : [4,5,6,7], 'BBB' : [10,20,30,40],'CCC' : [100,50,-30,-50]}); df

AAA  BBB  CCC
0    4   10  100
1    5   20   50
2    6   30  -30
3    7   40  -50

In [14]:
# And operation without assignment:
newseries = df.loc[(df['BBB'] < 25) & (df['CCC'] >= -40), 'AAA']; newseries

0    4
1    5
Name: AAA, dtype: int64

In [15]:
# Or operation without assignment:
newseries = df.loc[(df['BBB'] > 25) | (df['CCC'] >= -40), 'AAA']; newseries

0    4
1    5
2    6
3    7
Name: AAA, dtype: int64

In [16]:
# Or operation with assignment modifies the dataframe:
df.loc[(df['BBB'] > 25) | (df['CCC'] >= 75), 'AAA'] = 0.1; df

AAA  BBB  CCC
0  0.1   10  100
1  5.0   20   50
2  0.1   30  -30
3  0.1   40  -50

[Select the rows with data that's closest to a target value:](https://stackoverflow.com/questions/17758023/return-rows-in-a-dataframe-closest-to-a-user-defined-number)

In [17]:
df = pd.DataFrame({'AAA' : [4,5,6,7], 'BBB' : [10,20,30,40],'CCC' : [100,50,-30,-50]}); df

AAA  BBB  CCC
0    4   10  100
1    5   20   50
2    6   30  -30
3    7   40  -50

In [18]:
aValue = 43.0
df.loc[(df.CCC-aValue).abs().argsort()]

AAA  BBB  CCC
1    5   20   50
0    4   10  100
2    6   30  -30
3    7   40  -50

[Dynamically reduce a list of criteria using binary operators](https://stackoverflow.com/questions/21058254/pandas-boolean-operation-in-a-python-list/21058331)

In [19]:
df = pd.DataFrame({'AAA' : [4,5,6,7], 'BBB' : [10,20,30,40], 'CCC' : [100,50,-30,-50]}); df

AAA  BBB  CCC
0    4   10  100
1    5   20   50
2    6   30  -30
3    7   40  -50

In [20]:
Crit1 = df.AAA <= 5.5; Crit1

0     True
1     True
2    False
3    False
Name: AAA, dtype: bool

In [21]:
Crit2 = df.BBB == 10.0; Crit2

0     True
1    False
2    False
3    False
Name: BBB, dtype: bool

In [22]:
Crit3 = df.CCC > -40.0; Crit3

0     True
1     True
2     True
3    False
Name: CCC, dtype: bool

If you want to hard code a solution:

In [23]:
AllCrit = Crit1 & Crit2 & Crit3; AllCrit

0     True
1    False
2    False
3    False
dtype: bool

You may want to work with a list of dynamically built criteria:

In [24]:
CritList = [Crit1,Crit2,Crit3]; CritList

[0     True
 1     True
 2    False
 3    False
 Name: AAA, dtype: bool, 0     True
 1    False
 2    False
 3    False
 Name: BBB, dtype: bool, 0     True
 1     True
 2     True
 3    False
 Name: CCC, dtype: bool]

In [25]:
import functools

AllCrit = functools.reduce(lambda x,y: x & y, CritList); AllCrit

0     True
1    False
2    False
3    False
dtype: bool

In [26]:
df[AllCrit]

AAA  BBB  CCC
0    4   10  100

## [Selection](https://pandas.pydata.org/pandas-docs/stable/cookbook.html#selection)

### DataFrames

Ladies and gentleman, [The Indexing Documentation](https://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing)

[Pandas using row labels in boolean indexing](https://stackoverflow.com/questions/14725068/pandas-using-row-labels-in-boolean-indexing)

In [27]:
# Using both row labels and value conditionals:
df = pd.DataFrame({'AAA' : [4,5,6,7], 'BBB' : [10,20,30,40], 'CCC' : [100,50,-30,50]}); df

AAA  BBB  CCC
0    4   10  100
1    5   20   50
2    6   30  -30
3    7   40   50

In [28]:
df[(df.AAA <= 6) & (df.index.isin([0,2,4]))]

AAA  BBB  CCC
0    4   10  100
2    6   30  -30

[Use `loc` for label-oriented slicing and `iloc` for positional slicing](https://github.com/pandas-dev/pandas/issues/2904)

In [29]:
data = {'AAA' : [4,5,6,7], 'BBB' : [10,20,30,40], 'CCC' : [100,50,-30,50]}
pd.DataFrame(data)

AAA  BBB  CCC
0    4   10  100
1    5   20   50
2    6   30  -30
3    7   40   50

In [30]:
df = pd.DataFrame(data=data,index=['foo','bar','goo','car']); df

AAA  BBB  CCC
foo    4   10  100
bar    5   20   50
goo    6   30  -30
car    7   40   50

There are two explicit slicing methods and an available third option:
1. Positional-oriented ( Python slicing style : exclusive end )
2. Label-oriented ( Non-Python slicing style : inclusive end )
3. General ( Either slicing style : depends on slicing on labels or positions )

In [31]:
# Label-oriented:
df.loc['bar' : 'car']

AAA  BBB  CCC
bar    5   20   50
goo    6   30  -30
car    7   40   50

In [32]:
# Positional-oriented:
df.iloc[0:3]

AAA  BBB  CCC
foo    4   10  100
bar    5   20   50
goo    6   30  -30

Ambiguity arises when an index consists of integers with a non-zero start or non-unit increment.

In [33]:
# Begin index at 1 instead of 0
df2 = pd.DataFrame(data=data,index=[1,2,3,4]); df2

AAA  BBB  CCC
1    4   10  100
2    5   20   50
3    6   30  -30
4    7   40   50

In [34]:
df2.iloc[1:3]

AAA  BBB  CCC
2    5   20   50
3    6   30  -30

In [35]:
df2.loc[1:3]

AAA  BBB  CCC
1    4   10  100
2    5   20   50
3    6   30  -30

[Using the inverse operator `~` to take the complement of a mask](https://stackoverflow.com/questions/14986510/picking-out-elements-based-on-complement-of-indices-in-python-pandas)

In [36]:
df = pd.DataFrame({'AAA' : [4,5,6,7], 'BBB' : [10,20,30,40], 'CCC' : [100,50,-30,-50]}); df

AAA  BBB  CCC
0    4   10  100
1    5   20   50
2    6   30  -30
3    7   40  -50

In [37]:
df[~((df.AAA <= 6) & (df.index.isin([0,2,4])))]

AAA  BBB  CCC
1    5   20   50
3    7   40  -50

### Panels

[Extend a panel frame by transposing, adding a new dimension, and transposing back to the original dimensions](https://stackoverflow.com/questions/15364050/extending-a-pandas-panel-frame-along-the-minor-axis)

In [38]:
rng = pd.date_range('1/1/2018',periods=100,freq='D')

In [39]:
data = np.random.randn(100,4)

In [40]:
print(rng[:5])
print()
print(data[:5])
cols = ['A','B','C','D']; cols

DatetimeIndex(['2018-01-01', '2018-01-02', '2018-01-03', '2018-01-04',
               '2018-01-05'],
              dtype='datetime64[ns]', freq='D')

[[-1.59224323 -0.9970758   0.14979972 -0.60956883]
 [-1.59256133  0.01829805  0.33120536 -1.20042567]
 [ 1.02141864  1.0828622   0.40470015 -0.15697385]
 [ 0.46449768 -0.74013856  1.59890526  1.34548438]
 [ 0.2009951   1.6440299   0.10377347  0.15907162]]


['A', 'B', 'C', 'D']

In [41]:
# Another reason why Python is so wonderful:
df1, df2, df3 = pd.DataFrame(data, rng, cols), pd.DataFrame(data, rng, cols), pd.DataFrame(data, rng, cols)
df1[:5]

A         B         C         D
2018-01-01 -1.592243 -0.997076  0.149800 -0.609569
2018-01-02 -1.592561  0.018298  0.331205 -1.200426
2018-01-03  1.021419  1.082862  0.404700 -0.156974
2018-01-04  0.464498 -0.740139  1.598905  1.345484
2018-01-05  0.200995  1.644030  0.103773  0.159072

In [42]:
pf = pd.Panel({'df1':df1,'df2':df2,'df3':df3});pf

<class 'pandas.core.panel.Panel'>
Dimensions: 3 (items) x 100 (major_axis) x 4 (minor_axis)
Items axis: df1 to df3
Major_axis axis: 2018-01-01 00:00:00 to 2018-04-10 00:00:00
Minor_axis axis: A to D

In [43]:
pf.loc[:,:,'F'] = pd.DataFrame(data,rng,cols);pf

<class 'pandas.core.panel.Panel'>
Dimensions: 3 (items) x 100 (major_axis) x 5 (minor_axis)
Items axis: df1 to df3
Major_axis axis: 2018-01-01 00:00:00 to 2018-04-10 00:00:00
Minor_axis axis: A to F

### New Columns

[Create new columns using `applymap()`](https://stackoverflow.com/questions/16575868/efficiently-creating-additional-columns-in-a-pandas-dataframe-using-map)

In [44]:
df = pd.DataFrame({'AAA' : [1,2,1,3], 'BBB' : [1,1,2,2], 'CCC' : [2,1,3,1]}); df

AAA  BBB  CCC
0    1    1    2
1    2    1    1
2    1    2    3
3    3    2    1

In [45]:
source_cols = df.columns  # any subset would work
source_cols

Index(['AAA', 'BBB', 'CCC'], dtype='object')

In [46]:
new_cols = [str(x) + "_cat" for x in source_cols]
new_cols

['AAA_cat', 'BBB_cat', 'CCC_cat']

In [47]:
categories = { 1 : 'Alpha', 2 : 'Beta', 3 : 'Charlie' }
df[new_cols] = df[source_cols].applymap(categories.get); df

AAA  BBB  CCC  AAA_cat BBB_cat  CCC_cat
0    1    1    2    Alpha   Alpha     Beta
1    2    1    1     Beta   Alpha    Alpha
2    1    2    3    Alpha    Beta  Charlie
3    3    2    1  Charlie    Beta    Alpha

[Keep other columns when using `min()` with `groupby`](https://stackoverflow.com/questions/23394476/keep-other-columns-when-using-min-with-groupby)

In [48]:
df = pd.DataFrame({'AAA' : [1,1,1,2,2,2,3,3], 'BBB' : [2,1,3,4,5,1,2,3]}); df

AAA  BBB
0    1    2
1    1    1
2    1    3
3    2    4
4    2    5
5    2    1
6    3    2
7    3    3

In [49]:
# Method 1 -- use idxmin() to get the index of the mins:
df.loc[df.groupby('AAA')['BBB'].idxmin()]

AAA  BBB
1    1    1
5    2    1
6    3    2

In [52]:
# Method 2 -- sort the entries, then take the first of each.
# Notice that the resulting dataframe is the same except for the index.
df.sort_values(by='BBB').groupby('AAA', as_index=False).first()

AAA  BBB
0    1    1
1    2    1
2    3    2

## [MultiIndexing](https://pandas.pydata.org/pandas-docs/stable/cookbook.html#multiindexing)